---
- name: sysctl.conf
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: "fs.file-max"
      value: "360000"
    - name: "fs.suid_dumpable"
      value: "0"

    # 1.5.2 Ensure address space layout randomization (ASLR) is enabled
    - name: "kernel.randomize_va_space"
      value: "2"

    # 3.1.1 Ensure IP forwarding is disabled
    # Kubernetes の node ip_forward は有効にする (`1` にする) 必要がある
    # default は `0` のはず
    #- name: net.ipv4.ip_forward
    #  value: "0"
    #- name: net.ipv6.conf.all.forwarding
    #  value: "0"

    # 3.1.2 Ensure packet redirect sending is disabled 
    - name: "net.ipv4.conf.all.send_redirects"
      value: "0"
    - name: "net.ipv4.conf.default.send_redirects"
      value: "0"

    # 3.2.1 Ensure source routed packets are not accepted
    - name: "net.ipv4.conf.all.accept_source_route"
      value: "0"
    - name: "net.ipv4.conf.default.accept_source_route"
      value: "0"
    - name: "net.ipv6.conf.all.accept_source_route"
      value: "0"
    - name: "net.ipv6.conf.default.accept_source_route"
      value: "0"

    # 3.2.2 Ensure ICMP redirects are not accepted
    - name: "net.ipv4.conf.all.accept_redirects"
      value: "0"
    - name: "net.ipv4.conf.default.accept_redirects"
      value: "0"
    - name: "net.ipv6.conf.all.accept_redirects"
      value: "0"
    - name: "net.ipv6.conf.default.accept_redirects"
      value: "0"

    # 3.2.3 Ensure secure ICMP redirects are not accepted
    - name: "net.ipv4.conf.all.secure_redirects"
      value: "0"
    - name: "net.ipv4.conf.default.secure_redirects"
      value: "0"

    # 3.2.4 Ensure suspicious packets are logged
    - name: "net.ipv4.conf.all.log_martians"
      value: "1"
    - name: "net.ipv4.conf.default.log_martians"
      value: "1"

    # 3.2.5 Ensure broadcast ICMP requests are ignored
    - name: "net.ipv4.icmp_echo_ignore_broadcasts"
      value: "1"

    # 3.2.6 Ensure bogus ICMP responses are ignored
    - name: "net.ipv4.icmp_ignore_bogus_error_responses"
      value: "1"

    # 3.2.7 Ensure Reverse Path Filtering is enabled
    - name: "net.ipv4.conf.all.rp_filter"
      value: "1"
    - name: "net.ipv4.conf.default.rp_filter"
      value: "1"

    # 3.2.8 Ensure TCP SYN Cookies is enabled
    - name: "net.ipv4.tcp_syncookies"
      value: "1"

    # 3.2.9 Ensure IPv6 router advertisements are not accepted
    - name: "net.ipv6.conf.all.accept_ra"
      value: "0"
    - name: "net.ipv6.conf.default.accept_ra"
      value: "0"
