---
- name: Ensure SSH configuration for CIS
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    validate: "sshd -t -f %s"
    mode: 0600
    owner: root
    group: root
  loop:
    - { regexp: "^PermitRootLogin .*", line: "PermitRootLogin no" }
    - { regexp: "^ChallengeResponseAuthentication .*", line: "ChallengeResponseAuthentication no" }
    - { regexp: "^Protocol .*", line: "Protocol 2" }                                                                      
    - { regexp: "^LogLevel .*", line: "LogLevel INFO" }
    - { regexp: "^X11Forwarding .*", line: "X11Forwarding no" }
    - { regexp: "^MaxAuthTries .*", line: "MaxAuthTries 4" }
    - { regexp: "^IgnoreRhosts .*", line: "IgnoreRhosts yes" }
    - { regexp: "^HostbasedAuthentication .*", line: "HostbasedAuthentication no" }
    - { regexp: "^PermitUserEnvironment .*", line: "PermitUserEnvironment no" }
    - { regexp: "^MACs .*", line: "MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com" }
    - { regexp: "^ClientAliveInterval .*", line: "ClientAliveInterval 300" }
    - { regexp: "^ClientAliveCountMax .*", line: "ClientAliveCountMax 0" }
    - { regexp: "^LoginGraceTime .*", line: "LoginGraceTime 60" }
    #- { regexp: "^AllowGroups .*", line: "AllowGroups {{ allow_groups }}" }
    - { regexp: "^AllowGroups .*", line: "AllowGroups ec2-user" }
    - { regexp: "^Banner .*", line: "Banner /etc/issue.net" }
    - { regexp: "^PermitEmptyPasswords .*", line: "PermitEmptyPasswords no" }
    - { regexp: "^Ciphers .*", line: "Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr" }
    - { regexp: "^KexAlgorithms .*", line: "KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256" }


- name: create home directory when ssh login
  lineinfile:
    path: /etc/pam.d/sshd
    line: "session    required     pam_mkhomedir.so skel=/etc/skel/ umask=0027"


- name: restart sshd
  service:
    name: sshd
    state: restarted
    enabled: yes


- name: Ensure remote login warning banner is configured properly
  copy:
    src: issue
    dest: "{{ item }}"
  loop:
    - /etc/issue
    - /etc/issue.net


- name: Ensure default user shell timeout is 900 seconds or less
  lineinfile:
    line: TMOUT=600
    path: "{{ item }}"
  loop:
    - /etc/bashrc
    - /etc/profile


- name: Ensure password expiration is 365 days or less
  lineinfile:
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    path: /etc/login.defs
  loop:
    - line: "PASS_MAX_DAYS 90"
      regexp: "^PASS_MAX_DAYS"
    - line: "PASS_MIN_DAYS 7"
      regexp: "^PASS_MIN_DAYS"


- name: Ensure inactive password lock is 30 days or less
  command: useradd -D -f 30


- name: Ensure default user umask is 027 or more restrictive
  replace:
    path: "{{ item }}"
    regexp: "umask 022"
    replace: "umask 027"
  loop:
    - /etc/bashrc
    - /etc/profile


- name: Ensure rsyslog default file permissions configured
  lineinfile:
    line: '$FileCreateMode 0640'
    regexp: '^$FileCreateMode'
    path: /etc/rsyslog.conf
