---
- name: add audit kernel parameter
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="audit=1"'


- name: rebuild grub2 config
  command: /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg


- name: restrict /boot/grug2/grub.cfg permission
  file:
    path: /boot/grub2/grub.cfg
    owner: root
    group: root
    mode: 0600
